namespace infrastructure.services.mobs
{
    public enum MobType : ushort
    {
        None = 0,
        Zombie = 1,
        Skeleton = 2,
        TreeMan = 3,
        Amphibian = 4,
        CyclopsRed = 5,
        FireMan = 6,
        PumpkinMan = 7,
        CyclopsGreen = 8,
        CyclopsYellow = 9,
        CyclopsPurple = 10,
        Zombie2 = 11,
        Cannibal = 12,
        Creeper = 13,
        Druid = 14,
        Jason = 15,
        MagicMan = 16,
        MagicMan2 = 17,
        MagicMan3 = 18,
        MagicMan4 = 19,
        MagicSkeleton = 20,
        Monster1 = 21,
        Monster2 = 22,
        Monster3 = 23,
        Monster4 = 24,
        Pillager = 25,
        SkeletonKing = 26,
        SkeletonPirate = 27,
        Zombie3 = 28,
        Zombie4 = 29,
        ZombieWoman = 30,
    }
}