public enum BlockType : byte
{
    Air = 0,
    Grass = 1,
    Stone = 2,
    Cobblestone = 3,
    WoodLog = 4,
    WoodPlanks = 5,
    Sand = 6,
    Snow = 7,
    BrickWall = 8,
    StoneBrickWall = 9,
    Furnace = 10,
    DiamondOre = 11,
    RedOre = 12,
    LazuliOre = 13,
    IronOre = 14,
    GoldOre = 15,
    EmeraldOre = 16,
    CoalOre = 17,
    Dirt = 18,
    Leaves = 19,
    Water = 20,
}