using UnityEngine;
using UnityEditor;
using System.IO;
using System.Text;
using System.Collections.Generic;

public class GameResourcesGenerator : EditorWindow
{
    private static string resourcesPath = "Assets/Resources";
    private static string outputPath = "Assets/Scripts/GameResources.cs";

    [MenuItem("Tools/Generate Game Resources Script")]
    public static void Generate()
    {
        if (!Directory.Exists(resourcesPath))
        {
            Debug.LogError($"Resources directory not found at: {resourcesPath}");
            return;
        }

        // Создаем директорию для скрипта, если ее нет
        Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED FILE. DO NOT MODIFY.");
        sb.AppendLine("// This script was automatically generated by GameResourcesGenerator.");
        sb.AppendLine("// Any changes made to this file will be overwritten when regenerated.");
        sb.AppendLine();
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine();
        sb.AppendLine("public static class GameResources");
        sb.AppendLine("{");

        // Обрабатываем все файлы в папке Resources и подпапках
        ProcessDirectory(resourcesPath, sb, "");

        sb.AppendLine("}");

        File.WriteAllText(outputPath, sb.ToString());
        AssetDatabase.Refresh();

        Debug.Log($"GameResources script generated at: {outputPath}");
    }

    private static void ProcessDirectory(string directoryPath, StringBuilder sb, string currentNamespace)
    {
        string relativePath = directoryPath.Substring(resourcesPath.Length);
        string namespacePart = string.IsNullOrEmpty(relativePath)
            ? ""
            : $".{relativePath.Replace(Path.DirectorySeparatorChar, '.')}";

        // Получаем все файлы в текущей директории
        string[] files = Directory.GetFiles(directoryPath);
        HashSet<string> processedNames = new HashSet<string>();

        if (relativePath.Length > 0 && relativePath[0] == '\\')
        {
            relativePath = relativePath.Remove(0, 1);
        }

        foreach (string file in files)
        {
            if (file.EndsWith(".meta")) continue;

            string fileName = Path.GetFileNameWithoutExtension(file);
            string extension = Path.GetExtension(file).ToLower();
            string resourcePath = Path.Combine(relativePath, fileName).Replace('\\', '/');
            string methodName = ToSnakeCase(fileName);

            // Убедимся, что имена методов уникальны
            string uniqueMethodName = methodName;
            int counter = 1;
            while (processedNames.Contains(uniqueMethodName))
            {
                uniqueMethodName = $"{methodName}_{counter++}";
            }

            processedNames.Add(uniqueMethodName);

            switch (extension)
            {
                case ".png":
                case ".jpg":
                case ".jpeg":
                    sb.AppendLine(
                        $"    public static Texture2D {uniqueMethodName} => Resources.Load<Texture2D>(\"{resourcePath}\");");
                    break;
                case ".prefab":
                    sb.AppendLine(
                        $"    public static GameObject {uniqueMethodName} => Resources.Load<GameObject>(\"{resourcePath}\");");
                    break;
                case ".wav":
                case ".mp3":
                case ".ogg":
                    sb.AppendLine(
                        $"    public static AudioClip {uniqueMethodName} => Resources.Load<AudioClip>(\"{resourcePath}\");");
                    break;
                case ".mat":
                    sb.AppendLine(
                        $"    public static Material {uniqueMethodName} => Resources.Load<Material>(\"{resourcePath}\");");
                    break;
                case ".shader":
                    sb.AppendLine(
                        $"    public static Shader {uniqueMethodName} => Resources.Load<Shader>(\"{resourcePath}\");");
                    break;
                case ".asset":
                    sb.AppendLine(
                        $"    private static ScriptableObject _{uniqueMethodName};");
                    sb.AppendLine(
                        $"    public static T {uniqueMethodName}<T>() where T : ScriptableObject" +
                        "{" +
                        $"if (_{uniqueMethodName} == null)" +
                        $"  _{uniqueMethodName} = Resources.Load<T>(\"{resourcePath}\");" +
                        $"return _{uniqueMethodName} as T;" +
                        "}");
                    break;
                case ".txt":
                case ".json":
                case ".xml":
                case ".csv":
                    sb.AppendLine(
                        $"    public static TextAsset {uniqueMethodName} => Resources.Load<TextAsset>(\"{resourcePath}\");");
                    break;
                case ".fbx":
                case ".obj":
                case ".blend":
                    sb.AppendLine(
                        $"    public static Mesh {uniqueMethodName} => Resources.Load<Mesh>(\"{resourcePath}\");");
                    break;
                default:
                    sb.AppendLine(
                        $"    public static Object {uniqueMethodName} => Resources.Load<Object>(\"{resourcePath}\");");
                    break;
            }
        }

        // Рекурсивно обрабатываем поддиректории
        string[] directories = Directory.GetDirectories(directoryPath);
        foreach (string directory in directories)
        {
            string dirName = Path.GetFileName(directory);
            string newNamespace = string.IsNullOrEmpty(currentNamespace) ? dirName : $"{currentNamespace}.{dirName}";

            sb.AppendLine();
            sb.AppendLine($"    public static class {ToPascalCase(dirName)}");
            sb.AppendLine("    {");
            ProcessDirectory(directory, sb, newNamespace);
            sb.AppendLine("    }");
        }
    }

    private static string ToCamelCase(string input)
    {
        string pascal = ToPascalCase(input);
        if (string.IsNullOrEmpty(pascal)) return pascal;
        return char.ToLowerInvariant(pascal[0]) + pascal.Substring(1);
    }

    private static string ToPascalCase(string input)
    {
        if (string.IsNullOrEmpty(input))
            return input;

        StringBuilder sb = new StringBuilder();
        bool nextUpper = true;

        foreach (char c in input)
        {
            if (char.IsLetterOrDigit(c))
            {
                if (nextUpper)
                {
                    sb.Append(char.ToUpperInvariant(c));
                    nextUpper = false;
                }
                else
                {
                    sb.Append(char.ToLowerInvariant(c));
                }
            }
            else
            {
                nextUpper = true;
            }
        }

        // Если результат пустой, возвращаем пустую строку
        if (sb.Length == 0)
            return string.Empty;

        // Если первый символ не буква, добавляем префикс
        if (!char.IsLetter(sb[0]))
            sb.Insert(0, 'R');

        return sb.ToString();
    }

    private static string ToSnakeCase(string input)
    {
        if (string.IsNullOrEmpty(input))
            return input;

        StringBuilder sb = new StringBuilder();
        bool addedUnderscore = false;

        foreach (char c in input)
        {
            if (char.IsUpper(c))
            {
                // Добавляем подчеркивание перед заглавной буквой (кроме первой позиции)
                if (sb.Length > 0 && !addedUnderscore)
                {
                    sb.Append('_');
                }

                sb.Append(char.ToLowerInvariant(c));
                addedUnderscore = true;
            }
            else if (char.IsLetterOrDigit(c))
            {
                sb.Append(char.ToLowerInvariant(c));
                addedUnderscore = false;
            }
            else
            {
                // Заменяем небуквенно-цифровые символы на подчеркивания
                if (sb.Length > 0 && !addedUnderscore)
                {
                    sb.Append('_');
                    addedUnderscore = true;
                }
            }
        }

        return sb.ToString();
    }
}