// AUTO-GENERATED FILE. DO NOT MODIFY.
// This script was automatically generated by GameResourcesGenerator.
// Any changes made to this file will be overwritten when regenerated.

using UnityEngine;

public static class GameResources
{
    public static TextAsset billing_mode => Resources.Load<TextAsset>("BillingMode");
    private static ScriptableObject _dotween_settings;
    public static T dotween_settings<T>() where T : ScriptableObject{if (_dotween_settings == null)  _dotween_settings = Resources.Load<T>("DOTweenSettings");return _dotween_settings as T;}
    private static ScriptableObject _i2_languages;
    public static T i2_languages<T>() where T : ScriptableObject{if (_i2_languages == null)  _i2_languages = Resources.Load<T>("I2Languages");return _i2_languages as T;}
    private static ScriptableObject _platform_config;
    public static T platform_config<T>() where T : ScriptableObject{if (_platform_config == null)  _platform_config = Resources.Load<T>("Platform Config");return _platform_config as T;}
    public static GameObject project_context => Resources.Load<GameObject>("ProjectContext");

    public static class Data
    {
    private static ScriptableObject _connection_data;
    public static T connection_data<T>() where T : ScriptableObject{if (_connection_data == null)  _connection_data = Resources.Load<T>("Data/ConnectionData");return _connection_data as T;}
    public static TextAsset swear_words => Resources.Load<TextAsset>("Data/SwearWords");

    public static class Catalogs
    {
    private static ScriptableObject _currency_product_catalog;
    public static T currency_product_catalog<T>() where T : ScriptableObject{if (_currency_product_catalog == null)  _currency_product_catalog = Resources.Load<T>("Data/Catalogs/CurrencyProductCatalog");return _currency_product_catalog as T;}
    private static ScriptableObject _map_icons_catalog;
    public static T map_icons_catalog<T>() where T : ScriptableObject{if (_map_icons_catalog == null)  _map_icons_catalog = Resources.Load<T>("Data/Catalogs/MapIconsCatalog");return _map_icons_catalog as T;}
    private static ScriptableObject _mob_icons;
    public static T mob_icons<T>() where T : ScriptableObject{if (_mob_icons == null)  _mob_icons = Resources.Load<T>("Data/Catalogs/MobIcons");return _mob_icons as T;}
    private static ScriptableObject _quest_panel_colors;
    public static T quest_panel_colors<T>() where T : ScriptableObject{if (_quest_panel_colors == null)  _quest_panel_colors = Resources.Load<T>("Data/Catalogs/QuestPanelColors");return _quest_panel_colors as T;}
    private static ScriptableObject _rare_color_catalog;
    public static T rare_color_catalog<T>() where T : ScriptableObject{if (_rare_color_catalog == null)  _rare_color_catalog = Resources.Load<T>("Data/Catalogs/RareColorCatalog");return _rare_color_catalog as T;}
    private static ScriptableObject _resource_sprites;
    public static T resource_sprites<T>() where T : ScriptableObject{if (_resource_sprites == null)  _resource_sprites = Resources.Load<T>("Data/Catalogs/ResourceSprites");return _resource_sprites as T;}

    public static class Clan
    {
    private static ScriptableObject _dark_icons;
    public static T dark_icons<T>() where T : ScriptableObject{if (_dark_icons == null)  _dark_icons = Resources.Load<T>("Data/Catalogs/Clan/DarkIcons");return _dark_icons as T;}
    private static ScriptableObject _faction_catalog;
    public static T faction_catalog<T>() where T : ScriptableObject{if (_faction_catalog == null)  _faction_catalog = Resources.Load<T>("Data/Catalogs/Clan/FactionCatalog");return _faction_catalog as T;}
    private static ScriptableObject _faction_color_catalog;
    public static T faction_color_catalog<T>() where T : ScriptableObject{if (_faction_color_catalog == null)  _faction_color_catalog = Resources.Load<T>("Data/Catalogs/Clan/FactionColorCatalog");return _faction_color_catalog as T;}
    private static ScriptableObject _light_icons;
    public static T light_icons<T>() where T : ScriptableObject{if (_light_icons == null)  _light_icons = Resources.Load<T>("Data/Catalogs/Clan/LightIcons");return _light_icons as T;}
    }
    }

    public static class Character
    {
    private static ScriptableObject _armor_data;
    public static T armor_data<T>() where T : ScriptableObject{if (_armor_data == null)  _armor_data = Resources.Load<T>("Data/Character/ArmorData");return _armor_data as T;}
    private static ScriptableObject _hands_item_data;
    public static T hands_item_data<T>() where T : ScriptableObject{if (_hands_item_data == null)  _hands_item_data = Resources.Load<T>("Data/Character/HandsItemData");return _hands_item_data as T;}
    }

    public static class Inventory
    {
    private static ScriptableObject _auto_icon_dictionary;
    public static T auto_icon_dictionary<T>() where T : ScriptableObject{if (_auto_icon_dictionary == null)  _auto_icon_dictionary = Resources.Load<T>("Data/Inventory/AutoIconDictionary");return _auto_icon_dictionary as T;}
    private static ScriptableObject _item_database;
    public static T item_database<T>() where T : ScriptableObject{if (_item_database == null)  _item_database = Resources.Load<T>("Data/Inventory/Item Database");return _item_database as T;}

    public static class Items
    {
    private static ScriptableObject _helmet;
    public static T helmet<T>() where T : ScriptableObject{if (_helmet == null)  _helmet = Resources.Load<T>("Data/Inventory/Items/Helmet");return _helmet as T;}
    private static ScriptableObject _sword;
    public static T sword<T>() where T : ScriptableObject{if (_sword == null)  _sword = Resources.Load<T>("Data/Inventory/Items/Sword");return _sword as T;}

    public static class Armor
    {

    public static class R1leather
    {
    private static ScriptableObject _body;
    public static T body<T>() where T : ScriptableObject{if (_body == null)  _body = Resources.Load<T>("Data/Inventory/Items/Armor/1Leather/Body");return _body as T;}
    private static ScriptableObject _foot;
    public static T foot<T>() where T : ScriptableObject{if (_foot == null)  _foot = Resources.Load<T>("Data/Inventory/Items/Armor/1Leather/Foot");return _foot as T;}
    private static ScriptableObject _head;
    public static T head<T>() where T : ScriptableObject{if (_head == null)  _head = Resources.Load<T>("Data/Inventory/Items/Armor/1Leather/Head");return _head as T;}
    private static ScriptableObject _legs;
    public static T legs<T>() where T : ScriptableObject{if (_legs == null)  _legs = Resources.Load<T>("Data/Inventory/Items/Armor/1Leather/Legs");return _legs as T;}
    }

    public static class R2chainmail
    {
    private static ScriptableObject _body;
    public static T body<T>() where T : ScriptableObject{if (_body == null)  _body = Resources.Load<T>("Data/Inventory/Items/Armor/2Chainmail/Body");return _body as T;}
    private static ScriptableObject _foot;
    public static T foot<T>() where T : ScriptableObject{if (_foot == null)  _foot = Resources.Load<T>("Data/Inventory/Items/Armor/2Chainmail/Foot");return _foot as T;}
    private static ScriptableObject _head;
    public static T head<T>() where T : ScriptableObject{if (_head == null)  _head = Resources.Load<T>("Data/Inventory/Items/Armor/2Chainmail/Head");return _head as T;}
    private static ScriptableObject _legs;
    public static T legs<T>() where T : ScriptableObject{if (_legs == null)  _legs = Resources.Load<T>("Data/Inventory/Items/Armor/2Chainmail/Legs");return _legs as T;}
    }

    public static class R3iron
    {
    private static ScriptableObject _body;
    public static T body<T>() where T : ScriptableObject{if (_body == null)  _body = Resources.Load<T>("Data/Inventory/Items/Armor/3Iron/Body");return _body as T;}
    private static ScriptableObject _foot;
    public static T foot<T>() where T : ScriptableObject{if (_foot == null)  _foot = Resources.Load<T>("Data/Inventory/Items/Armor/3Iron/Foot");return _foot as T;}
    private static ScriptableObject _head;
    public static T head<T>() where T : ScriptableObject{if (_head == null)  _head = Resources.Load<T>("Data/Inventory/Items/Armor/3Iron/Head");return _head as T;}
    private static ScriptableObject _legs;
    public static T legs<T>() where T : ScriptableObject{if (_legs == null)  _legs = Resources.Load<T>("Data/Inventory/Items/Armor/3Iron/Legs");return _legs as T;}
    }

    public static class R4gold
    {
    private static ScriptableObject _body;
    public static T body<T>() where T : ScriptableObject{if (_body == null)  _body = Resources.Load<T>("Data/Inventory/Items/Armor/4Gold/Body");return _body as T;}
    private static ScriptableObject _foot;
    public static T foot<T>() where T : ScriptableObject{if (_foot == null)  _foot = Resources.Load<T>("Data/Inventory/Items/Armor/4Gold/Foot");return _foot as T;}
    private static ScriptableObject _head;
    public static T head<T>() where T : ScriptableObject{if (_head == null)  _head = Resources.Load<T>("Data/Inventory/Items/Armor/4Gold/Head");return _head as T;}
    private static ScriptableObject _legs;
    public static T legs<T>() where T : ScriptableObject{if (_legs == null)  _legs = Resources.Load<T>("Data/Inventory/Items/Armor/4Gold/Legs");return _legs as T;}
    }

    public static class R5diamond
    {
    private static ScriptableObject _body;
    public static T body<T>() where T : ScriptableObject{if (_body == null)  _body = Resources.Load<T>("Data/Inventory/Items/Armor/5Diamond/Body");return _body as T;}
    private static ScriptableObject _foot;
    public static T foot<T>() where T : ScriptableObject{if (_foot == null)  _foot = Resources.Load<T>("Data/Inventory/Items/Armor/5Diamond/Foot");return _foot as T;}
    private static ScriptableObject _head;
    public static T head<T>() where T : ScriptableObject{if (_head == null)  _head = Resources.Load<T>("Data/Inventory/Items/Armor/5Diamond/Head");return _head as T;}
    private static ScriptableObject _legs;
    public static T legs<T>() where T : ScriptableObject{if (_legs == null)  _legs = Resources.Load<T>("Data/Inventory/Items/Armor/5Diamond/Legs");return _legs as T;}
    }

    public static class R6netherite
    {
    private static ScriptableObject _body;
    public static T body<T>() where T : ScriptableObject{if (_body == null)  _body = Resources.Load<T>("Data/Inventory/Items/Armor/6Netherite/Body");return _body as T;}
    private static ScriptableObject _foot;
    public static T foot<T>() where T : ScriptableObject{if (_foot == null)  _foot = Resources.Load<T>("Data/Inventory/Items/Armor/6Netherite/Foot");return _foot as T;}
    private static ScriptableObject _head;
    public static T head<T>() where T : ScriptableObject{if (_head == null)  _head = Resources.Load<T>("Data/Inventory/Items/Armor/6Netherite/Head");return _head as T;}
    private static ScriptableObject _legs;
    public static T legs<T>() where T : ScriptableObject{if (_legs == null)  _legs = Resources.Load<T>("Data/Inventory/Items/Armor/6Netherite/Legs");return _legs as T;}
    }
    }

    public static class Food
    {
    private static ScriptableObject _beer;
    public static T beer<T>() where T : ScriptableObject{if (_beer == null)  _beer = Resources.Load<T>("Data/Inventory/Items/Food/Beer");return _beer as T;}
    private static ScriptableObject _berries;
    public static T berries<T>() where T : ScriptableObject{if (_berries == null)  _berries = Resources.Load<T>("Data/Inventory/Items/Food/Berries");return _berries as T;}
    private static ScriptableObject _bread;
    public static T bread<T>() where T : ScriptableObject{if (_bread == null)  _bread = Resources.Load<T>("Data/Inventory/Items/Food/Bread");return _bread as T;}
    private static ScriptableObject _bretzel;
    public static T bretzel<T>() where T : ScriptableObject{if (_bretzel == null)  _bretzel = Resources.Load<T>("Data/Inventory/Items/Food/Bretzel");return _bretzel as T;}
    private static ScriptableObject _bulgarian_pepper;
    public static T bulgarian_pepper<T>() where T : ScriptableObject{if (_bulgarian_pepper == null)  _bulgarian_pepper = Resources.Load<T>("Data/Inventory/Items/Food/Bulgarian pepper");return _bulgarian_pepper as T;}
    private static ScriptableObject _burger;
    public static T burger<T>() where T : ScriptableObject{if (_burger == null)  _burger = Resources.Load<T>("Data/Inventory/Items/Food/Burger");return _burger as T;}
    private static ScriptableObject _cake;
    public static T cake<T>() where T : ScriptableObject{if (_cake == null)  _cake = Resources.Load<T>("Data/Inventory/Items/Food/Cake");return _cake as T;}
    private static ScriptableObject _candy;
    public static T candy<T>() where T : ScriptableObject{if (_candy == null)  _candy = Resources.Load<T>("Data/Inventory/Items/Food/Candy");return _candy as T;}
    private static ScriptableObject _carrot;
    public static T carrot<T>() where T : ScriptableObject{if (_carrot == null)  _carrot = Resources.Load<T>("Data/Inventory/Items/Food/Carrot");return _carrot as T;}
    private static ScriptableObject _cheese;
    public static T cheese<T>() where T : ScriptableObject{if (_cheese == null)  _cheese = Resources.Load<T>("Data/Inventory/Items/Food/Cheese");return _cheese as T;}
    private static ScriptableObject _chiken;
    public static T chiken<T>() where T : ScriptableObject{if (_chiken == null)  _chiken = Resources.Load<T>("Data/Inventory/Items/Food/Chiken");return _chiken as T;}
    private static ScriptableObject _chocolate;
    public static T chocolate<T>() where T : ScriptableObject{if (_chocolate == null)  _chocolate = Resources.Load<T>("Data/Inventory/Items/Food/Chocolate");return _chocolate as T;}
    private static ScriptableObject _coffee;
    public static T coffee<T>() where T : ScriptableObject{if (_coffee == null)  _coffee = Resources.Load<T>("Data/Inventory/Items/Food/Coffee");return _coffee as T;}
    private static ScriptableObject _cucumber;
    public static T cucumber<T>() where T : ScriptableObject{if (_cucumber == null)  _cucumber = Resources.Load<T>("Data/Inventory/Items/Food/Cucumber");return _cucumber as T;}
    private static ScriptableObject _cupcake;
    public static T cupcake<T>() where T : ScriptableObject{if (_cupcake == null)  _cupcake = Resources.Load<T>("Data/Inventory/Items/Food/Cupcake");return _cupcake as T;}
    private static ScriptableObject _egg;
    public static T egg<T>() where T : ScriptableObject{if (_egg == null)  _egg = Resources.Load<T>("Data/Inventory/Items/Food/Egg");return _egg as T;}
    private static ScriptableObject _french_fries;
    public static T french_fries<T>() where T : ScriptableObject{if (_french_fries == null)  _french_fries = Resources.Load<T>("Data/Inventory/Items/Food/French fries");return _french_fries as T;}
    private static ScriptableObject _fried_egg;
    public static T fried_egg<T>() where T : ScriptableObject{if (_fried_egg == null)  _fried_egg = Resources.Load<T>("Data/Inventory/Items/Food/Fried egg");return _fried_egg as T;}
    private static ScriptableObject _fried_meat;
    public static T fried_meat<T>() where T : ScriptableObject{if (_fried_meat == null)  _fried_meat = Resources.Load<T>("Data/Inventory/Items/Food/Fried meat");return _fried_meat as T;}
    private static ScriptableObject _garlic;
    public static T garlic<T>() where T : ScriptableObject{if (_garlic == null)  _garlic = Resources.Load<T>("Data/Inventory/Items/Food/Garlic");return _garlic as T;}
    private static ScriptableObject _grape;
    public static T grape<T>() where T : ScriptableObject{if (_grape == null)  _grape = Resources.Load<T>("Data/Inventory/Items/Food/Grape");return _grape as T;}
    private static ScriptableObject _green_apple;
    public static T green_apple<T>() where T : ScriptableObject{if (_green_apple == null)  _green_apple = Resources.Load<T>("Data/Inventory/Items/Food/GreenApple");return _green_apple as T;}
    private static ScriptableObject _honey;
    public static T honey<T>() where T : ScriptableObject{if (_honey == null)  _honey = Resources.Load<T>("Data/Inventory/Items/Food/Honey");return _honey as T;}
    private static ScriptableObject _hot_dog;
    public static T hot_dog<T>() where T : ScriptableObject{if (_hot_dog == null)  _hot_dog = Resources.Load<T>("Data/Inventory/Items/Food/Hot dog");return _hot_dog as T;}
    private static ScriptableObject _ice_cream;
    public static T ice_cream<T>() where T : ScriptableObject{if (_ice_cream == null)  _ice_cream = Resources.Load<T>("Data/Inventory/Items/Food/Ice cream");return _ice_cream as T;}
    private static ScriptableObject _jam;
    public static T jam<T>() where T : ScriptableObject{if (_jam == null)  _jam = Resources.Load<T>("Data/Inventory/Items/Food/Jam");return _jam as T;}
    private static ScriptableObject _pancakes;
    public static T pancakes<T>() where T : ScriptableObject{if (_pancakes == null)  _pancakes = Resources.Load<T>("Data/Inventory/Items/Food/Pancakes");return _pancakes as T;}
    private static ScriptableObject _pasta;
    public static T pasta<T>() where T : ScriptableObject{if (_pasta == null)  _pasta = Resources.Load<T>("Data/Inventory/Items/Food/Pasta");return _pasta as T;}
    private static ScriptableObject _pie;
    public static T pie<T>() where T : ScriptableObject{if (_pie == null)  _pie = Resources.Load<T>("Data/Inventory/Items/Food/Pie");return _pie as T;}
    private static ScriptableObject _pizza;
    public static T pizza<T>() where T : ScriptableObject{if (_pizza == null)  _pizza = Resources.Load<T>("Data/Inventory/Items/Food/Pizza");return _pizza as T;}
    private static ScriptableObject _potato;
    public static T potato<T>() where T : ScriptableObject{if (_potato == null)  _potato = Resources.Load<T>("Data/Inventory/Items/Food/Potato");return _potato as T;}
    private static ScriptableObject _raw_meat;
    public static T raw_meat<T>() where T : ScriptableObject{if (_raw_meat == null)  _raw_meat = Resources.Load<T>("Data/Inventory/Items/Food/Raw meat");return _raw_meat as T;}
    private static ScriptableObject _red_apple;
    public static T red_apple<T>() where T : ScriptableObject{if (_red_apple == null)  _red_apple = Resources.Load<T>("Data/Inventory/Items/Food/RedApple");return _red_apple as T;}
    private static ScriptableObject _salad;
    public static T salad<T>() where T : ScriptableObject{if (_salad == null)  _salad = Resources.Load<T>("Data/Inventory/Items/Food/Salad");return _salad as T;}
    private static ScriptableObject _sausages;
    public static T sausages<T>() where T : ScriptableObject{if (_sausages == null)  _sausages = Resources.Load<T>("Data/Inventory/Items/Food/Sausages");return _sausages as T;}
    private static ScriptableObject _soup;
    public static T soup<T>() where T : ScriptableObject{if (_soup == null)  _soup = Resources.Load<T>("Data/Inventory/Items/Food/Soup");return _soup as T;}
    private static ScriptableObject _watermelon;
    public static T watermelon<T>() where T : ScriptableObject{if (_watermelon == null)  _watermelon = Resources.Load<T>("Data/Inventory/Items/Food/Watermelon");return _watermelon as T;}
    }

    public static class Potions
    {
    private static ScriptableObject _potion_1;
    public static T potion_1<T>() where T : ScriptableObject{if (_potion_1 == null)  _potion_1 = Resources.Load<T>("Data/Inventory/Items/Potions/Potion 1");return _potion_1 as T;}
    private static ScriptableObject _potion;
    public static T potion<T>() where T : ScriptableObject{if (_potion == null)  _potion = Resources.Load<T>("Data/Inventory/Items/Potions/Potion");return _potion as T;}
    }

    public static class Swords
    {
    private static ScriptableObject _diamond_sword;
    public static T diamond_sword<T>() where T : ScriptableObject{if (_diamond_sword == null)  _diamond_sword = Resources.Load<T>("Data/Inventory/Items/Swords/DiamondSword");return _diamond_sword as T;}
    private static ScriptableObject _gold_sword;
    public static T gold_sword<T>() where T : ScriptableObject{if (_gold_sword == null)  _gold_sword = Resources.Load<T>("Data/Inventory/Items/Swords/GoldSword");return _gold_sword as T;}
    private static ScriptableObject _iron_sword;
    public static T iron_sword<T>() where T : ScriptableObject{if (_iron_sword == null)  _iron_sword = Resources.Load<T>("Data/Inventory/Items/Swords/IronSword");return _iron_sword as T;}
    private static ScriptableObject _netherite_sword;
    public static T netherite_sword<T>() where T : ScriptableObject{if (_netherite_sword == null)  _netherite_sword = Resources.Load<T>("Data/Inventory/Items/Swords/NetheriteSword");return _netherite_sword as T;}
    private static ScriptableObject _stone_sword;
    public static T stone_sword<T>() where T : ScriptableObject{if (_stone_sword == null)  _stone_sword = Resources.Load<T>("Data/Inventory/Items/Swords/StoneSword");return _stone_sword as T;}
    private static ScriptableObject _wooden_sword;
    public static T wooden_sword<T>() where T : ScriptableObject{if (_wooden_sword == null)  _wooden_sword = Resources.Load<T>("Data/Inventory/Items/Swords/WoodenSword");return _wooden_sword as T;}
    }
    }
    }

    public static class Map
    {
    private static ScriptableObject _block_texture_data;
    public static T block_texture_data<T>() where T : ScriptableObject{if (_block_texture_data == null)  _block_texture_data = Resources.Load<T>("Data/Map/BlockTextureData");return _block_texture_data as T;}
    private static ScriptableObject _map_icon_catalog;
    public static T map_icon_catalog<T>() where T : ScriptableObject{if (_map_icon_catalog == null)  _map_icon_catalog = Resources.Load<T>("Data/Map/MapIconCatalog");return _map_icon_catalog as T;}

    public static class Blocks
    {
    private static ScriptableObject _air;
    public static T air<T>() where T : ScriptableObject{if (_air == null)  _air = Resources.Load<T>("Data/Map/Blocks/Air");return _air as T;}
    private static ScriptableObject _black_wool;
    public static T black_wool<T>() where T : ScriptableObject{if (_black_wool == null)  _black_wool = Resources.Load<T>("Data/Map/Blocks/BlackWool");return _black_wool as T;}
    private static ScriptableObject _blue_wool;
    public static T blue_wool<T>() where T : ScriptableObject{if (_blue_wool == null)  _blue_wool = Resources.Load<T>("Data/Map/Blocks/BlueWool");return _blue_wool as T;}
    private static ScriptableObject _bookshelf;
    public static T bookshelf<T>() where T : ScriptableObject{if (_bookshelf == null)  _bookshelf = Resources.Load<T>("Data/Map/Blocks/Bookshelf");return _bookshelf as T;}
    private static ScriptableObject _brick_stairs;
    public static T brick_stairs<T>() where T : ScriptableObject{if (_brick_stairs == null)  _brick_stairs = Resources.Load<T>("Data/Map/Blocks/BrickStairs");return _brick_stairs as T;}
    private static ScriptableObject _brick_wall;
    public static T brick_wall<T>() where T : ScriptableObject{if (_brick_wall == null)  _brick_wall = Resources.Load<T>("Data/Map/Blocks/BrickWall");return _brick_wall as T;}
    private static ScriptableObject _brown_wool;
    public static T brown_wool<T>() where T : ScriptableObject{if (_brown_wool == null)  _brown_wool = Resources.Load<T>("Data/Map/Blocks/BrownWool");return _brown_wool as T;}
    private static ScriptableObject _clay;
    public static T clay<T>() where T : ScriptableObject{if (_clay == null)  _clay = Resources.Load<T>("Data/Map/Blocks/Clay");return _clay as T;}
    private static ScriptableObject _coal_ore;
    public static T coal_ore<T>() where T : ScriptableObject{if (_coal_ore == null)  _coal_ore = Resources.Load<T>("Data/Map/Blocks/CoalOre");return _coal_ore as T;}
    private static ScriptableObject _cobblestone;
    public static T cobblestone<T>() where T : ScriptableObject{if (_cobblestone == null)  _cobblestone = Resources.Load<T>("Data/Map/Blocks/Cobblestone");return _cobblestone as T;}
    private static ScriptableObject _cobblestone_fence;
    public static T cobblestone_fence<T>() where T : ScriptableObject{if (_cobblestone_fence == null)  _cobblestone_fence = Resources.Load<T>("Data/Map/Blocks/CobblestoneFence");return _cobblestone_fence as T;}
    private static ScriptableObject _cobblestone_stairs;
    public static T cobblestone_stairs<T>() where T : ScriptableObject{if (_cobblestone_stairs == null)  _cobblestone_stairs = Resources.Load<T>("Data/Map/Blocks/CobblestoneStairs");return _cobblestone_stairs as T;}
    private static ScriptableObject _cyan_wool;
    public static T cyan_wool<T>() where T : ScriptableObject{if (_cyan_wool == null)  _cyan_wool = Resources.Load<T>("Data/Map/Blocks/CyanWool");return _cyan_wool as T;}
    private static ScriptableObject _diamond_ore;
    public static T diamond_ore<T>() where T : ScriptableObject{if (_diamond_ore == null)  _diamond_ore = Resources.Load<T>("Data/Map/Blocks/DiamondOre");return _diamond_ore as T;}
    private static ScriptableObject _diamonds_block;
    public static T diamonds_block<T>() where T : ScriptableObject{if (_diamonds_block == null)  _diamonds_block = Resources.Load<T>("Data/Map/Blocks/DiamondsBlock");return _diamonds_block as T;}
    private static ScriptableObject _dirt;
    public static T dirt<T>() where T : ScriptableObject{if (_dirt == null)  _dirt = Resources.Load<T>("Data/Map/Blocks/Dirt");return _dirt as T;}
    private static ScriptableObject _door;
    public static T door<T>() where T : ScriptableObject{if (_door == null)  _door = Resources.Load<T>("Data/Map/Blocks/Door");return _door as T;}
    private static ScriptableObject _emerald_block;
    public static T emerald_block<T>() where T : ScriptableObject{if (_emerald_block == null)  _emerald_block = Resources.Load<T>("Data/Map/Blocks/EmeraldBlock");return _emerald_block as T;}
    private static ScriptableObject _emerald_ore;
    public static T emerald_ore<T>() where T : ScriptableObject{if (_emerald_ore == null)  _emerald_ore = Resources.Load<T>("Data/Map/Blocks/EmeraldOre");return _emerald_ore as T;}
    private static ScriptableObject _error;
    public static T error<T>() where T : ScriptableObject{if (_error == null)  _error = Resources.Load<T>("Data/Map/Blocks/Error");return _error as T;}
    private static ScriptableObject _furnace;
    public static T furnace<T>() where T : ScriptableObject{if (_furnace == null)  _furnace = Resources.Load<T>("Data/Map/Blocks/Furnace");return _furnace as T;}
    private static ScriptableObject _glass;
    public static T glass<T>() where T : ScriptableObject{if (_glass == null)  _glass = Resources.Load<T>("Data/Map/Blocks/Glass");return _glass as T;}
    private static ScriptableObject _glowstone;
    public static T glowstone<T>() where T : ScriptableObject{if (_glowstone == null)  _glowstone = Resources.Load<T>("Data/Map/Blocks/Glowstone");return _glowstone as T;}
    private static ScriptableObject _gold_block;
    public static T gold_block<T>() where T : ScriptableObject{if (_gold_block == null)  _gold_block = Resources.Load<T>("Data/Map/Blocks/GoldBlock");return _gold_block as T;}
    private static ScriptableObject _gold_ore;
    public static T gold_ore<T>() where T : ScriptableObject{if (_gold_ore == null)  _gold_ore = Resources.Load<T>("Data/Map/Blocks/GoldOre");return _gold_ore as T;}
    private static ScriptableObject _grass;
    public static T grass<T>() where T : ScriptableObject{if (_grass == null)  _grass = Resources.Load<T>("Data/Map/Blocks/Grass");return _grass as T;}
    private static ScriptableObject _gray_wool;
    public static T gray_wool<T>() where T : ScriptableObject{if (_gray_wool == null)  _gray_wool = Resources.Load<T>("Data/Map/Blocks/GrayWool");return _gray_wool as T;}
    private static ScriptableObject _green_wool;
    public static T green_wool<T>() where T : ScriptableObject{if (_green_wool == null)  _green_wool = Resources.Load<T>("Data/Map/Blocks/GreenWool");return _green_wool as T;}
    private static ScriptableObject _half_brick_wall;
    public static T half_brick_wall<T>() where T : ScriptableObject{if (_half_brick_wall == null)  _half_brick_wall = Resources.Load<T>("Data/Map/Blocks/HalfBrickWall");return _half_brick_wall as T;}
    private static ScriptableObject _half_cobblestone;
    public static T half_cobblestone<T>() where T : ScriptableObject{if (_half_cobblestone == null)  _half_cobblestone = Resources.Load<T>("Data/Map/Blocks/HalfCobblestone");return _half_cobblestone as T;}
    private static ScriptableObject _half_nether_brick;
    public static T half_nether_brick<T>() where T : ScriptableObject{if (_half_nether_brick == null)  _half_nether_brick = Resources.Load<T>("Data/Map/Blocks/HalfNetherBrick");return _half_nether_brick as T;}
    private static ScriptableObject _half_sand;
    public static T half_sand<T>() where T : ScriptableObject{if (_half_sand == null)  _half_sand = Resources.Load<T>("Data/Map/Blocks/HalfSand");return _half_sand as T;}
    private static ScriptableObject _half_smooth_stone;
    public static T half_smooth_stone<T>() where T : ScriptableObject{if (_half_smooth_stone == null)  _half_smooth_stone = Resources.Load<T>("Data/Map/Blocks/HalfSmoothStone");return _half_smooth_stone as T;}
    private static ScriptableObject _half_stone_brick_wall;
    public static T half_stone_brick_wall<T>() where T : ScriptableObject{if (_half_stone_brick_wall == null)  _half_stone_brick_wall = Resources.Load<T>("Data/Map/Blocks/HalfStoneBrickWall");return _half_stone_brick_wall as T;}
    private static ScriptableObject _half_wood_planks;
    public static T half_wood_planks<T>() where T : ScriptableObject{if (_half_wood_planks == null)  _half_wood_planks = Resources.Load<T>("Data/Map/Blocks/HalfWoodPlanks");return _half_wood_planks as T;}
    private static ScriptableObject _hay;
    public static T hay<T>() where T : ScriptableObject{if (_hay == null)  _hay = Resources.Load<T>("Data/Map/Blocks/Hay");return _hay as T;}
    private static ScriptableObject _iron_block;
    public static T iron_block<T>() where T : ScriptableObject{if (_iron_block == null)  _iron_block = Resources.Load<T>("Data/Map/Blocks/IronBlock");return _iron_block as T;}
    private static ScriptableObject _iron_ore;
    public static T iron_ore<T>() where T : ScriptableObject{if (_iron_ore == null)  _iron_ore = Resources.Load<T>("Data/Map/Blocks/IronOre");return _iron_ore as T;}
    private static ScriptableObject _lazuli_ore;
    public static T lazuli_ore<T>() where T : ScriptableObject{if (_lazuli_ore == null)  _lazuli_ore = Resources.Load<T>("Data/Map/Blocks/LazuliOre");return _lazuli_ore as T;}
    private static ScriptableObject _leaves;
    public static T leaves<T>() where T : ScriptableObject{if (_leaves == null)  _leaves = Resources.Load<T>("Data/Map/Blocks/Leaves");return _leaves as T;}
    private static ScriptableObject _light_blue_wool;
    public static T light_blue_wool<T>() where T : ScriptableObject{if (_light_blue_wool == null)  _light_blue_wool = Resources.Load<T>("Data/Map/Blocks/LightBlueWool");return _light_blue_wool as T;}
    private static ScriptableObject _light_gray_wool;
    public static T light_gray_wool<T>() where T : ScriptableObject{if (_light_gray_wool == null)  _light_gray_wool = Resources.Load<T>("Data/Map/Blocks/LightGrayWool");return _light_gray_wool as T;}
    private static ScriptableObject _lime_wool;
    public static T lime_wool<T>() where T : ScriptableObject{if (_lime_wool == null)  _lime_wool = Resources.Load<T>("Data/Map/Blocks/LimeWool");return _lime_wool as T;}
    private static ScriptableObject _magenta_wool;
    public static T magenta_wool<T>() where T : ScriptableObject{if (_magenta_wool == null)  _magenta_wool = Resources.Load<T>("Data/Map/Blocks/MagentaWool");return _magenta_wool as T;}
    private static ScriptableObject _nether_brick;
    public static T nether_brick<T>() where T : ScriptableObject{if (_nether_brick == null)  _nether_brick = Resources.Load<T>("Data/Map/Blocks/NetherBrick");return _nether_brick as T;}
    private static ScriptableObject _nether_brick_stairs;
    public static T nether_brick_stairs<T>() where T : ScriptableObject{if (_nether_brick_stairs == null)  _nether_brick_stairs = Resources.Load<T>("Data/Map/Blocks/NetherBrickStairs");return _nether_brick_stairs as T;}
    private static ScriptableObject _obsidian;
    public static T obsidian<T>() where T : ScriptableObject{if (_obsidian == null)  _obsidian = Resources.Load<T>("Data/Map/Blocks/Obsidian");return _obsidian as T;}
    private static ScriptableObject _orange_wool;
    public static T orange_wool<T>() where T : ScriptableObject{if (_orange_wool == null)  _orange_wool = Resources.Load<T>("Data/Map/Blocks/OrangeWool");return _orange_wool as T;}
    private static ScriptableObject _pink_wool;
    public static T pink_wool<T>() where T : ScriptableObject{if (_pink_wool == null)  _pink_wool = Resources.Load<T>("Data/Map/Blocks/PinkWool");return _pink_wool as T;}
    private static ScriptableObject _purple_wool;
    public static T purple_wool<T>() where T : ScriptableObject{if (_purple_wool == null)  _purple_wool = Resources.Load<T>("Data/Map/Blocks/PurpleWool");return _purple_wool as T;}
    private static ScriptableObject _red_ore;
    public static T red_ore<T>() where T : ScriptableObject{if (_red_ore == null)  _red_ore = Resources.Load<T>("Data/Map/Blocks/RedOre");return _red_ore as T;}
    private static ScriptableObject _red_wool;
    public static T red_wool<T>() where T : ScriptableObject{if (_red_wool == null)  _red_wool = Resources.Load<T>("Data/Map/Blocks/RedWool");return _red_wool as T;}
    private static ScriptableObject _sand;
    public static T sand<T>() where T : ScriptableObject{if (_sand == null)  _sand = Resources.Load<T>("Data/Map/Blocks/Sand");return _sand as T;}
    private static ScriptableObject _smooth_stone;
    public static T smooth_stone<T>() where T : ScriptableObject{if (_smooth_stone == null)  _smooth_stone = Resources.Load<T>("Data/Map/Blocks/SmoothStone");return _smooth_stone as T;}
    private static ScriptableObject _snow;
    public static T snow<T>() where T : ScriptableObject{if (_snow == null)  _snow = Resources.Load<T>("Data/Map/Blocks/Snow");return _snow as T;}
    private static ScriptableObject _snow_carpet;
    public static T snow_carpet<T>() where T : ScriptableObject{if (_snow_carpet == null)  _snow_carpet = Resources.Load<T>("Data/Map/Blocks/SnowCarpet");return _snow_carpet as T;}
    private static ScriptableObject _stone;
    public static T stone<T>() where T : ScriptableObject{if (_stone == null)  _stone = Resources.Load<T>("Data/Map/Blocks/Stone");return _stone as T;}
    private static ScriptableObject _stone_brick_wall;
    public static T stone_brick_wall<T>() where T : ScriptableObject{if (_stone_brick_wall == null)  _stone_brick_wall = Resources.Load<T>("Data/Map/Blocks/StoneBrickWall");return _stone_brick_wall as T;}
    private static ScriptableObject _stone_brick_wall_stairs;
    public static T stone_brick_wall_stairs<T>() where T : ScriptableObject{if (_stone_brick_wall_stairs == null)  _stone_brick_wall_stairs = Resources.Load<T>("Data/Map/Blocks/StoneBrickWallStairs");return _stone_brick_wall_stairs as T;}
    private static ScriptableObject _water;
    public static T water<T>() where T : ScriptableObject{if (_water == null)  _water = Resources.Load<T>("Data/Map/Blocks/Water");return _water as T;}
    private static ScriptableObject _wheat;
    public static T wheat<T>() where T : ScriptableObject{if (_wheat == null)  _wheat = Resources.Load<T>("Data/Map/Blocks/Wheat");return _wheat as T;}
    private static ScriptableObject _white_wool;
    public static T white_wool<T>() where T : ScriptableObject{if (_white_wool == null)  _white_wool = Resources.Load<T>("Data/Map/Blocks/WhiteWool");return _white_wool as T;}
    private static ScriptableObject _wood_fence;
    public static T wood_fence<T>() where T : ScriptableObject{if (_wood_fence == null)  _wood_fence = Resources.Load<T>("Data/Map/Blocks/WoodFence");return _wood_fence as T;}
    private static ScriptableObject _wood_log;
    public static T wood_log<T>() where T : ScriptableObject{if (_wood_log == null)  _wood_log = Resources.Load<T>("Data/Map/Blocks/WoodLog");return _wood_log as T;}
    private static ScriptableObject _wood_planks;
    public static T wood_planks<T>() where T : ScriptableObject{if (_wood_planks == null)  _wood_planks = Resources.Load<T>("Data/Map/Blocks/WoodPlanks");return _wood_planks as T;}
    private static ScriptableObject _wood_stairs;
    public static T wood_stairs<T>() where T : ScriptableObject{if (_wood_stairs == null)  _wood_stairs = Resources.Load<T>("Data/Map/Blocks/WoodStairs");return _wood_stairs as T;}
    private static ScriptableObject _workbench;
    public static T workbench<T>() where T : ScriptableObject{if (_workbench == null)  _workbench = Resources.Load<T>("Data/Map/Blocks/Workbench");return _workbench as T;}
    private static ScriptableObject _yellow_wool;
    public static T yellow_wool<T>() where T : ScriptableObject{if (_yellow_wool == null)  _yellow_wool = Resources.Load<T>("Data/Map/Blocks/YellowWool");return _yellow_wool as T;}
    }

    public static class Icons
    {
    private static ScriptableObject _enemy_player;
    public static T enemy_player<T>() where T : ScriptableObject{if (_enemy_player == null)  _enemy_player = Resources.Load<T>("Data/Map/Icons/EnemyPlayer");return _enemy_player as T;}
    private static ScriptableObject _lumber;
    public static T lumber<T>() where T : ScriptableObject{if (_lumber == null)  _lumber = Resources.Load<T>("Data/Map/Icons/Lumber");return _lumber as T;}
    private static ScriptableObject _mine;
    public static T mine<T>() where T : ScriptableObject{if (_mine == null)  _mine = Resources.Load<T>("Data/Map/Icons/Mine");return _mine as T;}
    private static ScriptableObject _mob;
    public static T mob<T>() where T : ScriptableObject{if (_mob == null)  _mob = Resources.Load<T>("Data/Map/Icons/Mob");return _mob as T;}
    private static ScriptableObject _npc;
    public static T npc<T>() where T : ScriptableObject{if (_npc == null)  _npc = Resources.Load<T>("Data/Map/Icons/Npc");return _npc as T;}
    private static ScriptableObject _player;
    public static T player<T>() where T : ScriptableObject{if (_player == null)  _player = Resources.Load<T>("Data/Map/Icons/Player");return _player as T;}
    private static ScriptableObject _waypoint;
    public static T waypoint<T>() where T : ScriptableObject{if (_waypoint == null)  _waypoint = Resources.Load<T>("Data/Map/Icons/Waypoint");return _waypoint as T;}
    }

    public static class Meshes
    {
    private static ScriptableObject _cube;
    public static T cube<T>() where T : ScriptableObject{if (_cube == null)  _cube = Resources.Load<T>("Data/Map/Meshes/Cube");return _cube as T;}
    private static ScriptableObject _fence;
    public static T fence<T>() where T : ScriptableObject{if (_fence == null)  _fence = Resources.Load<T>("Data/Map/Meshes/Fence");return _fence as T;}
    private static ScriptableObject _half_cube;
    public static T half_cube<T>() where T : ScriptableObject{if (_half_cube == null)  _half_cube = Resources.Load<T>("Data/Map/Meshes/HalfCube");return _half_cube as T;}
    private static ScriptableObject _stairs;
    public static T stairs<T>() where T : ScriptableObject{if (_stairs == null)  _stairs = Resources.Load<T>("Data/Map/Meshes/Stairs");return _stairs as T;}
    private static ScriptableObject _water;
    public static T water<T>() where T : ScriptableObject{if (_water == null)  _water = Resources.Load<T>("Data/Map/Meshes/Water");return _water as T;}
    private static ScriptableObject _wheat;
    public static T wheat<T>() where T : ScriptableObject{if (_wheat == null)  _wheat = Resources.Load<T>("Data/Map/Meshes/Wheat");return _wheat as T;}
    private static ScriptableObject _сarpet;
    public static T сarpet<T>() where T : ScriptableObject{if (_сarpet == null)  _сarpet = Resources.Load<T>("Data/Map/Meshes/Сarpet");return _сarpet as T;}
    }
    }

    public static class Mobs
    {
    private static ScriptableObject _amphibian;
    public static T amphibian<T>() where T : ScriptableObject{if (_amphibian == null)  _amphibian = Resources.Load<T>("Data/Mobs/Amphibian");return _amphibian as T;}
    private static ScriptableObject _cannibal;
    public static T cannibal<T>() where T : ScriptableObject{if (_cannibal == null)  _cannibal = Resources.Load<T>("Data/Mobs/Cannibal");return _cannibal as T;}
    private static ScriptableObject _creeper;
    public static T creeper<T>() where T : ScriptableObject{if (_creeper == null)  _creeper = Resources.Load<T>("Data/Mobs/Creeper");return _creeper as T;}
    private static ScriptableObject _cyclops_red;
    public static T cyclops_red<T>() where T : ScriptableObject{if (_cyclops_red == null)  _cyclops_red = Resources.Load<T>("Data/Mobs/Cyclops Red");return _cyclops_red as T;}
    private static ScriptableObject _cyclops_green;
    public static T cyclops_green<T>() where T : ScriptableObject{if (_cyclops_green == null)  _cyclops_green = Resources.Load<T>("Data/Mobs/CyclopsGreen");return _cyclops_green as T;}
    private static ScriptableObject _cyclops_purple;
    public static T cyclops_purple<T>() where T : ScriptableObject{if (_cyclops_purple == null)  _cyclops_purple = Resources.Load<T>("Data/Mobs/CyclopsPurple");return _cyclops_purple as T;}
    private static ScriptableObject _cyclops_yellow;
    public static T cyclops_yellow<T>() where T : ScriptableObject{if (_cyclops_yellow == null)  _cyclops_yellow = Resources.Load<T>("Data/Mobs/CyclopsYellow");return _cyclops_yellow as T;}
    private static ScriptableObject _druid;
    public static T druid<T>() where T : ScriptableObject{if (_druid == null)  _druid = Resources.Load<T>("Data/Mobs/Druid");return _druid as T;}
    private static ScriptableObject _fire_man;
    public static T fire_man<T>() where T : ScriptableObject{if (_fire_man == null)  _fire_man = Resources.Load<T>("Data/Mobs/FireMan");return _fire_man as T;}
    private static ScriptableObject _jason;
    public static T jason<T>() where T : ScriptableObject{if (_jason == null)  _jason = Resources.Load<T>("Data/Mobs/Jason");return _jason as T;}
    private static ScriptableObject _magic_man;
    public static T magic_man<T>() where T : ScriptableObject{if (_magic_man == null)  _magic_man = Resources.Load<T>("Data/Mobs/MagicMan");return _magic_man as T;}
    private static ScriptableObject _magic_man2;
    public static T magic_man2<T>() where T : ScriptableObject{if (_magic_man2 == null)  _magic_man2 = Resources.Load<T>("Data/Mobs/MagicMan2");return _magic_man2 as T;}
    private static ScriptableObject _magic_man3;
    public static T magic_man3<T>() where T : ScriptableObject{if (_magic_man3 == null)  _magic_man3 = Resources.Load<T>("Data/Mobs/MagicMan3");return _magic_man3 as T;}
    private static ScriptableObject _magic_man4;
    public static T magic_man4<T>() where T : ScriptableObject{if (_magic_man4 == null)  _magic_man4 = Resources.Load<T>("Data/Mobs/MagicMan4");return _magic_man4 as T;}
    private static ScriptableObject _magic_skeleton;
    public static T magic_skeleton<T>() where T : ScriptableObject{if (_magic_skeleton == null)  _magic_skeleton = Resources.Load<T>("Data/Mobs/MagicSkeleton");return _magic_skeleton as T;}
    private static ScriptableObject _monster1;
    public static T monster1<T>() where T : ScriptableObject{if (_monster1 == null)  _monster1 = Resources.Load<T>("Data/Mobs/Monster1");return _monster1 as T;}
    private static ScriptableObject _monster2;
    public static T monster2<T>() where T : ScriptableObject{if (_monster2 == null)  _monster2 = Resources.Load<T>("Data/Mobs/Monster2");return _monster2 as T;}
    private static ScriptableObject _monster3;
    public static T monster3<T>() where T : ScriptableObject{if (_monster3 == null)  _monster3 = Resources.Load<T>("Data/Mobs/Monster3");return _monster3 as T;}
    private static ScriptableObject _monster4;
    public static T monster4<T>() where T : ScriptableObject{if (_monster4 == null)  _monster4 = Resources.Load<T>("Data/Mobs/Monster4");return _monster4 as T;}
    private static ScriptableObject _pillager;
    public static T pillager<T>() where T : ScriptableObject{if (_pillager == null)  _pillager = Resources.Load<T>("Data/Mobs/Pillager");return _pillager as T;}
    private static ScriptableObject _pumpkin_man;
    public static T pumpkin_man<T>() where T : ScriptableObject{if (_pumpkin_man == null)  _pumpkin_man = Resources.Load<T>("Data/Mobs/PumpkinMan");return _pumpkin_man as T;}
    private static ScriptableObject _skeleton;
    public static T skeleton<T>() where T : ScriptableObject{if (_skeleton == null)  _skeleton = Resources.Load<T>("Data/Mobs/Skeleton");return _skeleton as T;}
    private static ScriptableObject _skeleton_king;
    public static T skeleton_king<T>() where T : ScriptableObject{if (_skeleton_king == null)  _skeleton_king = Resources.Load<T>("Data/Mobs/SkeletonKing");return _skeleton_king as T;}
    private static ScriptableObject _skeleton_pirate;
    public static T skeleton_pirate<T>() where T : ScriptableObject{if (_skeleton_pirate == null)  _skeleton_pirate = Resources.Load<T>("Data/Mobs/SkeletonPirate");return _skeleton_pirate as T;}
    private static ScriptableObject _tree_man;
    public static T tree_man<T>() where T : ScriptableObject{if (_tree_man == null)  _tree_man = Resources.Load<T>("Data/Mobs/TreeMan");return _tree_man as T;}
    private static ScriptableObject _zombie_2;
    public static T zombie_2<T>() where T : ScriptableObject{if (_zombie_2 == null)  _zombie_2 = Resources.Load<T>("Data/Mobs/Zombie 2");return _zombie_2 as T;}
    private static ScriptableObject _zombie;
    public static T zombie<T>() where T : ScriptableObject{if (_zombie == null)  _zombie = Resources.Load<T>("Data/Mobs/Zombie");return _zombie as T;}
    private static ScriptableObject _zombie3;
    public static T zombie3<T>() where T : ScriptableObject{if (_zombie3 == null)  _zombie3 = Resources.Load<T>("Data/Mobs/Zombie3");return _zombie3 as T;}
    private static ScriptableObject _zombie4;
    public static T zombie4<T>() where T : ScriptableObject{if (_zombie4 == null)  _zombie4 = Resources.Load<T>("Data/Mobs/Zombie4");return _zombie4 as T;}
    private static ScriptableObject _zombie_woman;
    public static T zombie_woman<T>() where T : ScriptableObject{if (_zombie_woman == null)  _zombie_woman = Resources.Load<T>("Data/Mobs/ZombieWoman");return _zombie_woman as T;}
    }

    public static class Notifications
    {
    private static ScriptableObject _notification_data;
    public static T notification_data<T>() where T : ScriptableObject{if (_notification_data == null)  _notification_data = Resources.Load<T>("Data/Notifications/NotificationData");return _notification_data as T;}
    }
    }

    public static class Platforms
    {
    private static ScriptableObject _editor;
    public static T editor<T>() where T : ScriptableObject{if (_editor == null)  _editor = Resources.Load<T>("Platforms/Editor");return _editor as T;}
    private static ScriptableObject _google_play;
    public static T google_play<T>() where T : ScriptableObject{if (_google_play == null)  _google_play = Resources.Load<T>("Platforms/GooglePlay");return _google_play as T;}
    private static ScriptableObject _ru_store;
    public static T ru_store<T>() where T : ScriptableObject{if (_ru_store == null)  _ru_store = Resources.Load<T>("Platforms/RuStore");return _ru_store as T;}
    private static ScriptableObject _vk;
    public static T vk<T>() where T : ScriptableObject{if (_vk == null)  _vk = Resources.Load<T>("Platforms/VK");return _vk as T;}
    private static ScriptableObject _yandex_games;
    public static T yandex_games<T>() where T : ScriptableObject{if (_yandex_games == null)  _yandex_games = Resources.Load<T>("Platforms/YandexGames");return _yandex_games as T;}
    }

    public static class Prefabs
    {
    public static GameObject audio => Resources.Load<GameObject>("Prefabs/Audio");

    public static class Environment
    {
    public static GameObject npc => Resources.Load<GameObject>("Prefabs/Environment/NPC");

    public static class Chests
    {
    public static GameObject chest_from_mob => Resources.Load<GameObject>("Prefabs/Environment/Chests/ChestFromMob");
    }

    public static class House
    {
    public static GameObject house_enter => Resources.Load<GameObject>("Prefabs/Environment/House/HouseEnter");
    }

    public static class Lumber
    {
    public static GameObject lumber => Resources.Load<GameObject>("Prefabs/Environment/Lumber/Lumber");
    }

    public static class Mine
    {
    public static GameObject mine_enter => Resources.Load<GameObject>("Prefabs/Environment/Mine/MineEnter");
    }
    }

    public static class Map
    {
    public static GameObject chunk => Resources.Load<GameObject>("Prefabs/Map/Chunk");
    public static GameObject map_service => Resources.Load<GameObject>("Prefabs/Map/MapService");
    public static GameObject water => Resources.Load<GameObject>("Prefabs/Map/Water");
    }

    public static class Mobs
    {
    public static GameObject mob => Resources.Load<GameObject>("Prefabs/Mobs/Mob");

    public static class Models
    {
    public static GameObject humanoid => Resources.Load<GameObject>("Prefabs/Mobs/Models/Humanoid");
    public static GameObject humanoid_rounded => Resources.Load<GameObject>("Prefabs/Mobs/Models/HumanoidRounded");
    }
    }

    public static class Player
    {
    public static GameObject enemy => Resources.Load<GameObject>("Prefabs/Player/Enemy");
    public static GameObject new_cape => Resources.Load<GameObject>("Prefabs/Player/NewCape");
    public static GameObject old_cape => Resources.Load<GameObject>("Prefabs/Player/OldCape");
    public static GameObject player => Resources.Load<GameObject>("Prefabs/Player/Player");
    public static GameObject player_old => Resources.Load<GameObject>("Prefabs/Player/PlayerOld");

    public static class Handitems
    {
    public static GameObject potion => Resources.Load<GameObject>("Prefabs/Player/HandItems/Potion");
    }
    }

    public static class Transport
    {
    public static GameObject enemy_transport => Resources.Load<GameObject>("Prefabs/Transport/EnemyTransport");
    public static GameObject transport => Resources.Load<GameObject>("Prefabs/Transport/Transport");

    public static class Models
    {
    public static GameObject horse => Resources.Load<GameObject>("Prefabs/Transport/Models/Horse");
    }
    }

    public static class Ui
    {

    public static class Chat
    {
    public static GameObject message => Resources.Load<GameObject>("Prefabs/Ui/Chat/Message");
    }

    public static class Clan
    {
    public static GameObject buff => Resources.Load<GameObject>("Prefabs/Ui/Clan/Buff");
    public static GameObject clan_icon => Resources.Load<GameObject>("Prefabs/Ui/Clan/ClanIcon");
    public static GameObject craft => Resources.Load<GameObject>("Prefabs/Ui/Clan/Craft");
    public static GameObject craft_slot => Resources.Load<GameObject>("Prefabs/Ui/Clan/CraftSlot");
    public static GameObject history => Resources.Load<GameObject>("Prefabs/Ui/Clan/History");
    public static GameObject member => Resources.Load<GameObject>("Prefabs/Ui/Clan/Member");
    }

    public static class Crafts
    {
    public static GameObject craft => Resources.Load<GameObject>("Prefabs/Ui/Crafts/Craft");
    public static GameObject craft_slot => Resources.Load<GameObject>("Prefabs/Ui/Crafts/CraftSlot");
    }

    public static class Inventory
    {
    public static GameObject add_slot => Resources.Load<GameObject>("Prefabs/Ui/Inventory/AddSlot");
    public static GameObject equip_slot => Resources.Load<GameObject>("Prefabs/Ui/Inventory/EquipSlot");
    public static GameObject item => Resources.Load<GameObject>("Prefabs/Ui/Inventory/Item");
    public static GameObject locked_slot => Resources.Load<GameObject>("Prefabs/Ui/Inventory/LockedSlot");
    public static GameObject slot => Resources.Load<GameObject>("Prefabs/Ui/Inventory/Slot");

    public static class Quickslots
    {
    public static GameObject quick_slot => Resources.Load<GameObject>("Prefabs/Ui/Inventory/QuickSlots/QuickSlot");
    }
    }

    public static class Map
    {
    public static GameObject filter => Resources.Load<GameObject>("Prefabs/Ui/Map/Filter");
    public static GameObject marker => Resources.Load<GameObject>("Prefabs/Ui/Map/Marker");
    }

    public static class Notifications
    {
    public static GameObject notification => Resources.Load<GameObject>("Prefabs/Ui/Notifications/Notification");
    }

    public static class Npc
    {
    public static GameObject item_to_purchase => Resources.Load<GameObject>("Prefabs/Ui/Npc/ItemToPurchase");
    }

    public static class Quests
    {
    public static GameObject item_reward => Resources.Load<GameObject>("Prefabs/Ui/Quests/ItemReward");
    public static GameObject objective => Resources.Load<GameObject>("Prefabs/Ui/Quests/Objective");
    public static GameObject quest_panel => Resources.Load<GameObject>("Prefabs/Ui/Quests/QuestPanel");
    public static GameObject resource_reward => Resources.Load<GameObject>("Prefabs/Ui/Quests/ResourceReward");
    }

    public static class Shop
    {
    public static GameObject cape => Resources.Load<GameObject>("Prefabs/Ui/Shop/Cape");
    public static GameObject currency => Resources.Load<GameObject>("Prefabs/Ui/Shop/Currency");
    public static GameObject skin => Resources.Load<GameObject>("Prefabs/Ui/Shop/Skin");
    public static GameObject transport => Resources.Load<GameObject>("Prefabs/Ui/Shop/Transport");
    }
    }
    }

    public static class Sounds
    {
    private static ScriptableObject _footstep_dirt;
    public static T footstep_dirt<T>() where T : ScriptableObject{if (_footstep_dirt == null)  _footstep_dirt = Resources.Load<T>("Sounds/FootstepDirt");return _footstep_dirt as T;}
    private static ScriptableObject _footstep_grass;
    public static T footstep_grass<T>() where T : ScriptableObject{if (_footstep_grass == null)  _footstep_grass = Resources.Load<T>("Sounds/FootstepGrass");return _footstep_grass as T;}
    private static ScriptableObject _footstep_metal;
    public static T footstep_metal<T>() where T : ScriptableObject{if (_footstep_metal == null)  _footstep_metal = Resources.Load<T>("Sounds/FootstepMetal");return _footstep_metal as T;}
    private static ScriptableObject _footstep_sand;
    public static T footstep_sand<T>() where T : ScriptableObject{if (_footstep_sand == null)  _footstep_sand = Resources.Load<T>("Sounds/FootstepSand");return _footstep_sand as T;}
    private static ScriptableObject _footstep_snow;
    public static T footstep_snow<T>() where T : ScriptableObject{if (_footstep_snow == null)  _footstep_snow = Resources.Load<T>("Sounds/FootstepSnow");return _footstep_snow as T;}
    private static ScriptableObject _footstep_stone;
    public static T footstep_stone<T>() where T : ScriptableObject{if (_footstep_stone == null)  _footstep_stone = Resources.Load<T>("Sounds/FootstepStone");return _footstep_stone as T;}
    private static ScriptableObject _footstep_wood;
    public static T footstep_wood<T>() where T : ScriptableObject{if (_footstep_wood == null)  _footstep_wood = Resources.Load<T>("Sounds/FootstepWood");return _footstep_wood as T;}
    private static ScriptableObject _jump;
    public static T jump<T>() where T : ScriptableObject{if (_jump == null)  _jump = Resources.Load<T>("Sounds/Jump");return _jump as T;}
    private static ScriptableObject _land;
    public static T land<T>() where T : ScriptableObject{if (_land == null)  _land = Resources.Load<T>("Sounds/Land");return _land as T;}
    }
}
